baseURL: "https://abhay.rs/blog"
title: 'Everything Engineering'
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  series: series
  tag: tags

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 'Everything Engineering'
  description: "We don't care if it's irrelevant, we care if it's engineering."
  keywords: [Blog, Engineering]
  author: Abhay
  assets:
    favicon: "https://abhay.rs/blog/favicon.svg"
  images: ["https://abhay.rs/blog/favicon.svg"]
  DateFormat: "2006, January 2"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  label:
    text: "Everything Engineering"
    iconSVG: '<svg style="margin-bottom: -0.3em;border-radius: 0;" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" width="30" height="30"><svg width="30" height="30" viewBox="0 0 99.682 99.682" xmlns="http://www.w3.org/2000/svg"><path d="M0 10.807v78.19h46.972V73.438H15.657V57.731h23.486v-15.61H15.657V26.416h31.315v-15.61zM99.682 10.807v78.19H52.71V73.438h31.315V57.731H60.539v-15.61h23.486V26.416H52.71v-15.61z" fill="currentColor"></path></svg><style>@media (prefers-color-scheme: light) { :root { filter: none; } } </style></svg>'

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog, where we don't care if it's irrelevant, we care if it's engineering.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/swayambhu_dev"
    - name: github
      url: "https://github.com/rathod-sahaab"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  editPost:
    URL: "https://github.com/rathod-sahaab/blog/edit/dev/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: series
      name: series
      url: /series/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: portfolio
      name: abhay.rs
      url: https://abhay.rs
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    renderer:
      unsafe: true
